project:
  type: website
  output-dir: docs

website:
  title: "Pipeline NPL"
  favicon: attachments/favicon.png
  sidebar:
    tools:
      - href: 'https://github.com/MarioC0093'
        icon: github
        text: My repositories
      - href: 'https://www.linkedin.com/in/mario-camacho-b98462ab/'
        icon: linkedin
        text: "LinkedIn"
  twitter-card: true
  navbar:
    left:
      - href: 'https://github.com/MarioC0093/NPL-Python/'
        text: Home
      - href: about.html
        text: About
      - href: 'https://github.com/MarioC0093/NPL-Python/issues'
        icon: github
        text: Report an issue
    right:
      - href: 'https://buymeacoffee.com/marioc0093'
        icon: rocket-takeoff
        text: Buy me a coffee
  page-footer:
    center: 
      - text: "License"
        href: LICENSE.html

abstract: |
  La aplicación de nuevas fuentes de Inteligencia Artificial en el lenguaje humano está en auge desde la aparición de las IA Generativas de texto.
  Es por ello que se necesita tener un pipeline con los primeros pasos de NPL que debemos mantener en la resolución de problemas de mayor complejida.

keywords: ["npl","quijote"]

format:
  html:
    code-link: TRUE
    css: styles.css
    toc: true
    toc-title: "Índice"
    toc-location: left
    toc-expand: TRUE
    toc-depth: 8
    number-sections: TRUE
    theme: style.css
    page-layout: full

editor: visual
page-layout: full
code-fold: true
warning: false